CREATE TABLE USER_SUBSCRIPTION_PAYMENT (
    user_payment_order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_subscriber_mobile_number VARCHAR2(15) NOT NULL,
    current_time TIMESTAMP,
    user_name VARCHAR2(50),
    user_subscription_charges NUMBER,
    user_order_status VARCHAR2(20),
    razorpay_user_payment_order_id VARCHAR2(50),
    PRIMARY KEY (user_payment_order_id)
);

CREATE TABLE ADVERTISER_PAYMENT (
    advertiser_payment_order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    advertiser_mobile_number VARCHAR2(15) NOT NULL,
    current_time TIMESTAMP,
    advertiser_name VARCHAR2(50),
    location VARCHAR2(100),
    target_advertisement_charges NUMBER,
    advertiser_order_status VARCHAR2(20),
    razorpay_advertiser_payment_order_id VARCHAR2(50),
    PRIMARY KEY (advertiser_payment_order_id)
);
